name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.0.0
  pdf: ^3.10.1
  printing: ^5.10.0
  excel: ^2.0.3
  url_launcher: ^6.1.10
  http: ^0.13.6
  firebase_core: ^2.10.0
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.0        # opcional (recomendado)
  firebase_storage: ^11.1.0    # opcional (para fotos)
  shared_preferences: ^2.1.1
  connectivity_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/logo.png
    - assets/usuarios.json
    - assets/productores.json
